---
name: Release Digital Ocean 1-Click

on:
  release:
    types: [published]

  push:
    paths:
      - "DigitalOceanMarketplace/**"

  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Login to Azure - CI Subscription
        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@c86ced0dc8c9daeecf057a6333e6f318db9c5a2b
        with:
          keyvault: "bitwarden-ci"
          secrets: "digital-ocean-api-key"

      - name: Set version from version.json
        id: set-version
        run: |
          VERSION=$(grep '^ *"coreVersion":' version.json \
            | awk -F\: '{ print $2 }' \
            | sed -e 's/,$//' -e 's/^"//' -e 's/"$//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Hashicorp Packer
        uses: hashicorp/setup-packer@ae6b3ed3bec089bbfb576ab7d714df7cbc4b88a4 # v2.0.0

      - name: Build Digital Ocean Image
        env:
          DIGITALOCEAN_TOKEN: ${{ steps.retrieve-secrets.outputs.digital-ocean-api-key }}
          DIGITALOCEAN_IMG_VERSION: ${{ steps.set-version.outputs.version }}
        working-directory: ./DigitalOceanMarketplace
        run: |
          packer version
          packer init -upgrade marketplace-image.pkr.hcl
          packer build marketplace-image.pkr.hcl

      - name: Install doctl
        if: ${{ github.event_name != 'release' && github.event_name != 'workflow_dispatch' }}
        uses: digitalocean/action-doctl@ba7726ed64a9c5eb774152b1ea03bf67ee81ad6e # v2.3.0
        with:
          token: ${{ steps.retrieve-secrets.outputs.digital-ocean-api-key }}

      - name: Digital Ocean Image Cleanup
        working-directory: ./DigitalOceanMarketplace
        if: ${{ github.event_name != 'release' && github.event_name != 'workflow_dispatch' }}
        run: |
          # Get the ID from the snapshot build.
          DO_ARTIFACT=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)

          # Force remove the snapshot
          doctl compute image delete $DO_ARTIFACT -f
